export const GOT_ALL_BOOKMARKS = 'GOT_ALL_BOOKMARKS';
export const GOT_ALL_SPORTS = 'GOT_ALL_SPORTS';
export const GET_APITOKEN='GET_APITOKEN';
export const GOT_ALL_USERS='GOT_ALL_USERS';
export const GOT_PAYMENTS='GOT_PAYMENTS';
export const GOT_CLIENT='GOT_CLIENT';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGOUT_USER = 'LOGOUT_USER';